shopingcart/cart_app/urls.py
from django.urls import path

app_name = 'cart_app'

from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('ful_remove/<int:product_id>/', views.ful_remove, name='ful_remove'),
]

shopingcart/search_app/urls.py
from django.urls import path


app_name = 'search_app'

from .import views

urlpatterns = [

    path('', views.search_result, name='search_result')

]

shopingcart/shopingcart/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopingcart_app.urls', namespace='shopingcart_app')),
    path('search/', include('search_app.urls', namespace='search_app')),
    path('cart/', include('cart_app.urls',namespace='cart_app')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopingcart/shopingcart_app/urls.py
from django.urls import path

app_name = 'shopingcart_app'

from shopingcart_app import views

urlpatterns = [

    path('', views.allprodcat, name='allprodcat'),
    path('home/<slug:c_slug>/', views.allprodcat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proddetail, name='prodcatedetail')
]

shopingcart/cart_app/models.py
from django.db import models

# Create your models here.
from shopingcart_app.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class Cartitem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Cartitem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

shopingcart/search_app/models.py
from django.db import models

# Create your models here.

shopingcart/shopingcart_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    disc = models.TextField(blank=True)
    img = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def geturl(self):
        return reverse('shopingcart_app:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    disc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shopingcart_app:prodcatedetail', args=[self.category.slug , self.slug])

    def __str__(self):
        return '{}'.format(self.name)

shopingcart/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404

from shopingcart_app.models import Product
from .models import Cart, Cartitem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=cart_id(request))
        cart.save(),
    try:
        cart_item = Cartitem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except Cartitem.DoesNotExist:
        cart_item = Cartitem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
        cart_items = Cartitem.objects.filter(cart=cart, active=True)
        for cart_i in cart_items:
            total += (cart_i.product.price * cart_i.quantity)
            counter += cart_i.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', {'cart_items': cart_items, 'total': total, 'counter': counter})


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cartitem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_detail')


def ful_remove(request, product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cartitem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

shopingcart/search_app/views.py
from django.shortcuts import render, redirect
from shopingcart_app.models import Product
from django.db.models import Q


def search_result(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q', '')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(disc__contains=query))
    return render(request, 'search.html', dict(query=query, products=products))

shopingcart/shopingcart_app/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.


def allprodcat(request, c_slug=None):
    c_page = None
    product_list = None
    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        product_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        product_list = Product.objects.all().filter(available=True)
    paginator = Paginator(product_list, 4)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        product = paginator.page(page)
    except (EmptyPage, InvalidPage):
        product = paginator.page(paginator.num_pages)
    return render(request, "category.html", {'category': c_page, 'products': product})


def proddetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

shopingcart/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/2617d75ebc.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">

<div>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}

</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

</div>
</body>
</html>

shopingcart/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
cart page

{% endblock %}
{% block title %}
    Cart
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 justify-content">
                <div class="my_cart_card">
                        {% if not cart_items %}
                        <div>
                            <div class="text-center">
                               <br>
                               <h1 class="text-center my_title">
                                Your Cart is empty
                               </h1>
                               <br>
                                <p class="text-center"> Click <a href="{% url 'shopingcart_app:allprodcat' %}">here</a>to return to home page </p>

                            </div>
                        </div>
                            {% else %}
                            <div class="row">
                            <div class="col-md-8">
                            <table class="table my_custom_table">
                            <thead class="my_custom_thead">
                            <tr>
                                <th class="text-center" style="position:relative;left:250px;top:0px;font-size:20px;">
                                        cart

                                </th>

                            </tr>

                            </thead>
                            <tbody>
                            {% for cart_item in cart_items %}
                            <tr>
                                <td class="text-left col-md-2 col-lg-2 col-xl-2">


                                    <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.img.url}}" alt="***" style="width: 8rem; height:100px; border-radius:5px;"></a>



<!--                                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.img.url}}" alt="***"></a>-->

                                </td>
                                <td class="text-left col-md-2 col-lg-2 col-xl-2">
                                    {{cart_item.product.name}}
                                    <br>
                                     Price: ₹{{cart_item.product.price}}
                                    <br>
                                    Qty: {{cart_item.quantity}}*{{cart_item}}

                                 </td>
                                <td class="text-left col-md-2 col-lg-2 col-xl-2">
                                ₹ {{cart_item.sub_total}}
                                </td>
                                {% if cart_item.quantity < cart_item.product.stock %}
                                <td>
                                    <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-plus"></i></a>&nbsp;
                                    <a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                                    &nbsp;<a href="{% url 'cart_app:ful_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash"></i></a>
                                </td>
                                {% else %}
                                <td>

                                <a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                                &nbsp;<a href="{% url  'cart_app:ful_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash"></i></a>
                                </td>
                                {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>


                            </div>
                            </div>


      </div>
      </div>
        <div class="col-md-6 justify-content">
    <table class="my_cart_checkout">
        <thead>
        <tr>
            <th style="font-size:26px;position:absolute;top:50px;left:250px; text-transform:uppercase;">
                Checkout

            </th>

        </tr>

        </thead>
        <tbody>
        <tr>
            <td style="align-text: center; justify-item:center;">

                <br>
                <p style="padding-left:20px;font-size:15px;position:absolute; top:100px;text-transform:uppercase;">please review your cart items before proceedeing to payment.</p>
                <p style="padding-left:20px;font-size:15px;position:absolute; top:150px;text-transform:uppercase;">your total amount :₹{{total}}</p>
                <div style="color:#0a0a0a;">
                    |<br>
                    |<br>
                    |<br>
                    |<br>|<br>|<br>|<br>|<br>|<br>|<br>|<br>|<br>|<br>|<br>
                    |<br>|<br>|<br>|<br>|<br>|<br>|<br>|<br>|<br>|<br>|<br>
                    <div>
        <a href="{% url 'shopingcart_app:allprodcat' %}" class="btn btn-block" style="background-color:#b0aeae; color:#000000;font_style:bold;">proceed to pay</a>
    </div>


                </div>
            </td>
        </tr>
        </tbody>

    </table>



</div>







{% endif %}


</div>
</div>
{% endblock %}

shopingcart/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.disc|truncatewords:150}}
    {% else %}
        Welcome to Random Shop
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }}-Random Shop
    {% else %}
        see our random products
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
        <div>
            <div class="row my_row_class" >
                <div class="mx_auto">
                <a href="{% url 'shopingcart_app:allprodcat' %}">Link to All Products by Category</a>
            </div>
                </div>
        </div>
        {% endif %}

<div class="cat_img">
    <div class="mx_auto">
        {% if category %}
        <div class="cat_image_container">
            <img class="cat_image" src="{{category.img.url}}" alt="{{category.name}}" style="border-radius: 15px; height: 60vh;position: relative; top:-4em;">
            <div class="overlay_text" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);font-family: fantasy; text-align: center; color: CFC2AC; padding: 0px; font-size:95px;text-transform:uppercase; text-weight:800;">
                {{ category.name }}
            </div>
        </div>
    </div>
</div>
    <br>
<div>
    <h1 class="text-center my_title">
        {{ category.name }}
    </h1>
    <p class="text-justify">
        {{ category.disc}}
    </p>
</div>
    {% else %}
<div>
<!--    <img class="cat_image cat_image_padding " src="{% static 'img/banner.jpg' %}" alt="banner" width="2000px" height="600px">-->
</div>
                <div class="image-container">
                    <div class="banner-text">

							<h1 class="overlay-text">RANDOM SHOP</h1>

                    </div>
                </div>
<br>
<div>
    <h1 class="text-center my_title">Our Products</h1>
    <p class="text-justify" >When using Lorem Ipsum for creating dummy content for your newly created website, you can select the text formats you want from the tool. Like, words, sentences, or paragraphs. , you can select whether you want HTML markup in your dummy content or not Then, you can choose the number of words and paragraphs for your dummy content and execute the plan accordingly. You can use this tool at incrementors.com for free.</p>
</div>
    {% endif %}
<!--<div class="container">-->
<!--    <div>-->
<!--        {% for product in products  %}-->
<!--        <div>-->
<!--            <div>-->
<!--                <div>-->
<!--                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.img.url}}" alt="{{product.name}}"  width="200px" height="200px"></a>-->
<!--            <div>-->
<!--                <h4>{{product.name}}</h4>-->
<!--                <h6>{{product.price}}</h6>-->
<!--            </div>-->
<!--            </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        {% endfor %}-->
<!--    </div>-->
<!--</div>-->
<!-- -&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;-->
<div class="container">
    <div class="row">
        {% for product in products.object_list %}
        <div class="col-md-3">
            <div class="card">
                <figure>

                     <a href="{{product.get_url}}"><img  class="pho_to" src="{{product.img.url}}" style="height: 63vh;" alt="---"></a>
                </figure>
                <section class="details">

                    <a href="{{product.geturl}}"></a>
                    <div class="min-details">
                        <h1>{{ product.name }}</h1>
                        <h1 class="price">₹{{ product.price }}</h1>
                    </div>
                </section>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>

        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light {% if product.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>

{% endblock %}

shopingcart/templates/footer.html
<div class="wrapper">
        <footer>
            &copy; Random shop pvt ltd. All rights reserved
        </footer>
</div>

shopingcart/templates/header.html
<!--{% load static %}-->
<!--<div class="logo">-->
<!--<header>-->

<!--    <a href="{% url 'shopingcart_app:allprodcat' %}"></a>-->
<!--    <img src="{% static 'img/logo.png' %}" alt="logo" width="30px" >-->

<!--</header>-->
<!--</div>-->

shopingcart/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
hiii
</body>
</html>

shopingcart/templates/navbar.html
<div class="container">
<nav id="primary_nav_wrap">
    <ul>
        <li class="current-menu-item"><a href="{% url 'shopingcart_app:allprodcat' %}">Home</a></li>
        <li><a href="#">Updates</a></li>
        <li class="{% if 'shopingcart_app' in request.path %} active {% endif %}"><a href="{% url 'shopingcart_app:allprodcat' %}">All products</a>
            <ul>
                {% for cat in links %}
                <li><a href="{{cat.geturl}}">{{cat.name}}</a></li>
                {% endfor %}
            </ul>
        </li>
        <li><a href="#">About</a>

        </li>
        {% if item_count > 0 %}
        <li><a href="{% url 'cart_app:cart_detail'%}"><i class="fa-solid fa-cart-plus" style="color: #d6d6d6; width:1.5em;"></i>
            ({{item_count}})</a>
        </li>
        {% endif %}
<!--         search bar -->
        <li>

            <form action="{% url 'search_app:search_result' %}"  method="get">
            <div class="wrap">

              <div class="search" >

                  <input type="text" class="searchTerm" placeholder="type here..." name="q">

                  <button type="submit" class="searchButton">
                     <i class="fa fa-search"></i>
                 </button>
             </div>
           </div>
            </form>

        </li>
    </ul>
</nav>
<br><br><br><br>
<table>
    <tr>

    </tr>
</table>
</div>









<!--<nav>-->
<!--  <ul>-->
<!--    <li><a href="{% url 'shopingcart_app:allprodcat' %}">All products</a></li>-->
<!--    {% for cat in links %}-->

<!--    <li><a href="{{cat.geturl}}">{{cat.name}}</a></li>-->
<!--    {% endfor %}-->
<!--  </ul>-->
<!--</nav>-->

shopingcart/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.disc|truncatewords:150}}



{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }}-Random Shop

    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_product_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shopingcart_app:allprodcat' %}"Home></a>|<a href="{{product.category.geturl}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<div class="card">
      <div class="card__title">
        <div class="icon">
<br>
<div class="row">
    <div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6  text-center">
        <div class="product__photo" >
		<div class="photo-container">
			<div class="photo-main">

				<img src="{{product.img.url}}" alt="{{product.name}}">
			</div>

		</div>
	</div>
    </div>
    </div>
    <div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <h1 class="my_product_title">{{product.name}}</h1>
            <p style="font-size:32px;"><b>₹{{product.price}}</b></p>
            <p class="text-justify my_prod_disc " style="font-size:22px;">{{product.disc}}</p>
            {% if product.stock <= 0  %}
            <p class="text-justify my_prod_disc " style="font-size:18px; color:#fff5f5;"> <b> Out of Stock</b></p>
            {% else %}
            <div>
            <a href="{% url 'cart_app:add_cart' product.id %} "><button class="buy--btn">ADD TO CART</button></a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
            </div>
      </div>
</div>
{% endblock %}

shopingcart/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
WE have Random Products

{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center search_text">you have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col-md-3">
            <div class="card">
                <figure>

                     <a href="{{product.get_url}}"><img  class="pho_to" src="{{product.img.url}}" alt="---"></a>
                </figure>
                <section class="details">

                    <a href="{{product.geturl}}"></a>
                    <div class="min-details">
                        <h1>{{product.name}}</h1>
                        <h1 class="price">₹{{product.price}}</h1>
                    </div>
                </section>
            </div>
        </div>

    </div>


    {% empty %}
<div class="row mx-auto">
    <p class="text-center"> 0 result found</p>
</div>
{% endfor %}
</div>
{% endblock %}